name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Download Docker image
      run: docker pull ikarimovkh/exercise1:latest
      
    - name: Stop and remove existing container (if running)
      run: docker stop exercise1 || true && docker rm exercise1 || true
      
    - name: Run Docker container
      run: docker run -d --name exercise1 -p 3000:3000 ikarimovkh/exercise1:latest

