name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner here
    steps:
      - name: Pull Docker Image
        run: docker pull ikarimovkh/exercise1:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop your-container-name || true
          docker rm your-container-name || true

      - name: Run Docker Container
        run: docker run -d --name your-container-name -p 3000:3000 ikarimovkh/exercise1:latest
