name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Download Docker image
      run: docker pull your-dockerhub-username/your-app-name:latest
      
    - name: Stop and remove existing container (if running)
      run: docker stop your-container-name || true && docker rm your-container-name || true
      
    - name: Run Docker container
      run: docker run -d --name your-container-name -p 3000:3000 your-dockerhub-username/your-app-name:latest

