name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Docker Image
        run: docker pull ikarimovkh/exercise1:latest

      - name: Run Container
        run: docker run -d -p 3000:8080 ikarimovkh/exercise1:latest
