name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Docker image
      run: |
        #docker build -t ikarimovkh/exercise1:latest .
        docker build -t ikarimovkh/exercise1:latest .
      
    - name: Push Docker image to DockerHub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ikarimovkh/exercise1
        tags: latest
      
    
