name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/your-app-name:latest .
        docker build -t your-dockerhub-username/your-app-name:$(git rev-parse --short HEAD) .
      
    - name: Push Docker image to DockerHub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: your-dockerhub-username/your-app-name
        tags: latest, $(git rev-parse --short HEAD)
      
    - name: Run Docker container
      run: docker run -p 3000:3000 your-dockerhub-username/your-app-name:latest

