name: CI/CD Sequence

on:
  push:
    branches:
      - main

jobs:
  ci-cd-sequence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run CI job
      - name: CI
        run: |
          cd .github/workflows
          bash ci.yml

      # Run CD job if CI job succeeds
      - name: CD
        if: success()
        run: |
          cd .github/workflows
          bash cd.yml

      # Handle failure
      - name: Handle Failures
        if: failure()
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - CI/CD job failed in repository $GITHUB_REPOSITORY" >> failure_log.txt

      # Ensure web app accessibility
      - name: Ensure Web App Accessibility
        run: |
          # Add your command to ensure web app accessibility on port 3000
