name: CI/CD Sequence

on:
  push:
    branches:
      - main

jobs:
  ci-cd-sequence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CI
        needs: ./.github/workflows/ci.yml

      - name: Run CD
        if: success()
        needs: ./.github/workflows/cd.yml

      - name: Handle Failures
        if: failure()
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - CI/CD job failed in repository $GITHUB_REPOSITORY" >> failure_log.txt

      - name: Ensure Web App Accessibility
        run: |
          # Add your command to ensure web app accessibility on port 3000
