name: Deploy to Remote Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Docker container from Docker Hub
        run: |
          docker pull ikarimovkh/exercise1:latest

      - name: Deploy container to remote machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}  # Or use ssh key
          script: |
            docker run -d -p 3000:3000 ikarimovkh/exercise1:latest

